### ISSUE TITLE
Email reports after the end of each campaign

### ISSUE THREAD

**Issue by Ivshti** [AmbireTech/adex-platform#145]
should include the following information:

* total time span
* Total spend
* average CPM
* average CTR and CPC
* performance by day/hour (graph, could be SVGs)

And maybe this:

* performance by geographical location
* performance by ad unit
* performance by publisher

**Comment by rori4** [comment]
As we have integrated mautic this should be quite easy now. All we need to do is to create a custom email template and send tokens from the relayer for example for the specific user and the data that we want to show.

For future reference:
API ->` POST /emails/ID/contact/CONTACT_ID/send` - https://developer.mautic.org/#send-email-to-contact
https://www.youtube.com/watch?v=QCIE2SRf3gU&ab_channel=MauticCommunity
