### ISSUE TITLE
Email notifications when targeting doesn't match supply

### ISSUE THREAD

**Issue by dmngdsm** [AmbireTech/adex-platform#263]
**Is your feature request related to a problem? Please describe.**
Problem: Most users want to use the platform like any other and play around with targeting, but our supply is still not enough to cover lots of categories and options. The same users often choose "Show only if targeting matches" and their campaign get stuck on 0% distribution and users panic. 

**Describe the solution you'd like**
We've discussed the need of drip campaigns and system notification emails  before, so we may use this case might to start  with.
We can set triggers for when targeting doesn't match supply and push emails to users with advice to try wider targeting or something.

**Describe alternatives you've considered**
Even better than email (why not both actually) would be in-app notification center/tab. 

#406

**Comment by Ivshti** [comment]
related to #405
