### ISSUE TITLE
Use Google Vision API (or similar API) to auto categorize ads

### ISSUE THREAD

**Issue by Ivshti** [AmbireTech/adex-platform#40]
This can actually be applied on multiple levels of the stack, including the SDK/validator stack; to allow stuff like "exclude pornography from my site"

**Comment by rori4** [comment]
This can also be used when uploading your ad units and you can get suggestions for categories/tags for targeting. They also provide with the API percentage accuracy. Here is an example with a dog food banner: 
![dog food example](https://user-images.githubusercontent.com/22402693/67872664-f8a8d580-fb3a-11e9-929b-7baad37cfb6b.png)

**Comment by Ivshti** [comment]
that would be pretty awesome

**Comment by rori4** [comment]
@Ivshti We can also use https://cloud.google.com/natural-language/docs/classifying-text which can classify webpages with confidence percentage. This can be used in publisher side

**Comment by Ivshti** [comment]
yep, that's a great idea!

**Comment by rori4** [comment]
I am just leaving the NodeJS API docummentation here for future reference as it was hard to find:
[https://googleapis.dev/nodejs/vision/latest/index.html](https://googleapis.dev/nodejs/vision/latest/index.html)

**Comment by rori4** [comment]
Currently we are quite accurate in recognizing adult content and categorizing ads on advertiser side.. The default API does miss some of the times but I have created a sequence to categorize the ad based on target url, text on picture and overall labels gathered by google vision. Then we go through google-language api to categorize the text that describes the picture, the text on the picture and the website we want to send the visitors, which works quite well.

For publishers we need to know on which website they are going to publish their ad so we can perform the category suggestion. Then we can allow the iframe to show the ad only that url. So based on the provided URL we can categorize the website content.

Here are the categories used: [https://cloud.google.com/natural-language/docs/categories](https://cloud.google.com/natural-language/docs/categories)

**Comment by rori4** [comment]
related: https://github.com/AdExNetwork/adex-relayer/issues/66
